// ignore_for_file: public_member_api_docs, sort_constructors_first
class Personality {
  int id;
  String title;
  String subtitle;
  String logo;
  String focus;
  String discription;

  String fameType;
  List<String> careers;
  List<String> celebrities;

  Personality({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.logo,
    required this.focus,
    required this.discription,
    required this.fameType,
    required this.careers,
    required this.celebrities,
  });
}

List<Personality> allPersonalities = [
  Personality(
    id: 1,
    title: 'ISTJ',
    subtitle: 'Logical Assimilators',
    logo: 'assets/personality-logo/ISTJ.png',
    focus: 'Use attention to detail to get the job done',
    discription: '',
    fameType: 'The Investigator/Inspector',
    careers: [
      'Management',
      'Administration',
      'Law Enforcement',
      'Accounting',
    ],
    celebrities: [
      'Queen Elizabeth II',
      'Harry Truman',
      'Evander Holyfield',
      'Jack Nicklaus',
      'Cliff Clavin (Cheers)',
    ],
  ),
  Personality(
    id: 2,
    title: 'ISTP',
    subtitle: 'Practical Analyzers',
    logo: 'assets/personality-logo/ISTP.png',
    focus: 'Work hands-on with data or things and analyze',
    discription: '',
    fameType: 'The Athlete/Crafter',
    careers: [
      'Skilled Trade',
      'Agriculture',
      'Law Enforcement',
      'Military',
      'Technical Fields',
    ],
    celebrities: [
      'Ted Williams',
      'Bruce Lee',
      'Roger Clemens',
      'Larry Bird',
      'Michael Jordan',
      'Allen Iverson',
    ],
  ),
  Personality(
    id: 3,
    title: 'ESTP',
    subtitle: 'Logical Responders',
    logo: 'assets/personality-logo/ESTP.png',
    focus: 'Take action, work hands-on and attend to details',
    discription: '',
    fameType: 'The Opportunist/Promoter',
    careers: [
      'Marketing',
      'Skilled Trades',
      'Business',
      'Law Enforcements',
    ],
    celebrities: [
      'Ernest Hemingway',
      'Lucille Ball',
      'Pedro Martinez',
      'Eddie Murphy',
      'Madonna',
      'Donald Trump',
    ],
  ),
  Personality(
    id: 4,
    title: 'ESTJ',
    subtitle: 'Practical Expeditors',
    logo: 'assets/personality-logo/ESTJ.png',
    focus: 'Use logic and organization of the facts to get tasks done',
    discription: '',
    fameType: 'The Supervisor',
    careers: [
      'Management',
      'Administration',
      'Law Enforcement',
    ],
    celebrities: [
      'George W. Bush',
      'Nolan Ryan',
      'Judge Judy',
      'Dr. Laura Schlesinger',
      'Lucy (Peanuts character)',
    ],
  ),
  Personality(
    id: 5,
    title: 'ISFJ',
    subtitle: 'Compassionate Assimilators',
    logo: 'assets/personality-logo/ISFJ.png',
    focus: 'Personally help people behind the senses',
    discription: '',
    fameType: 'The Assistant/Protector',
    careers: [
      'Education',
      'Health Care',
      'Religious Settings',
    ],
    celebrities: [
      'Louisa May Alcott',
      'David Copperfield Ophelia (Hamlet)',
      'Johnny Carson',
      'Jerry Seinfeld',
      'Captain America',
    ],
  ),
  Personality(
    id: 6,
    title: 'ISFP',
    subtitle: 'Practical Enhancers',
    logo: 'assets/personality-logo/ISFP.png',
    focus:
        'Use gentle nature and attention to detail in service-related positions',
    discription: '',
    fameType: 'The Artisan/Composer',
    careers: [
      'Health Care',
      'Business',
      'Law Enforcement',
    ],
    celebrities: [
      'Mozart',
      'Neil Simon',
      'Paul McCartney',
      'Paul Pierce',
      'Brooke Shields',
    ],
  ),
  Personality(
    id: 7,
    title: 'ESFP',
    subtitle: 'Compassionate Responders',
    logo: 'assets/personality-logo/ESFP.png',
    focus: 'Use outgoing nature and enthusiasm with practical needs',
    discription: '',
    fameType: 'The Entertainer/Performer',
    careers: [
      'Health Care',
      'Teaching',
      'Child Care',
      'Skilled Trades',
    ],
    celebrities: [
      'Bob Hope',
      'Goldie Hawn',
      'Kyle Petty',
      'Magic Johnson',
      'Charles Barkley',
      'Bill Clinton',
    ],
  ),
  Personality(
    id: 8,
    title: 'ESFJ',
    subtitle: 'Practical Contributors',
    logo: 'assets/personality-logo/ESFJ.png',
    focus: 'Use their personal concern to provide service to others',
    discription: '',
    fameType: 'The Facilitator/Provider',
    careers: [
      'Education',
      'Health Care',
      'Religion',
    ],
    celebrities: [
      'George Washington',
      'Barbara Walters',
      'Terry Bradshaw',
      'Mary Tyler Moore',
      'Sally Field',
      'Monica (Friends)',
    ],
  ),
  Personality(
    id: 9,
    title: 'INFJ',
    subtitle: 'Compassionate Visionaries',
    logo: 'assets/personality-logo/INFJ.png',
    focus:
        'Facilitate other\'s emotional, intellectual or spritual development',
    discription: '',
    fameType: 'The Wordsmith/Counselor',
    careers: [
      'Religion',
      'Counsiling',
      'Teaching',
      'Arts',
    ],
    celebrities: [
      'Aristophanes',
      'Mohandas Gandhi',
      'Eleanor Roosevelt',
      'Michael Landon',
      'Queen Noor',
    ],
  ),
  Personality(
    id: 10,
    title: 'INFP',
    subtitle: 'Insightful Enhanchcers',
    logo: 'assets/personality-logo/INFP.png',
    focus: 'Use creativity to honor or support their values',
    discription: '',
    fameType: 'The Idealist/Healer',
    careers: [
      'Counseling',
      'Writing',
      'Arts',
    ],
    celebrities: [
      'Helen Keller',
      'Fred Rogers (Mister Rogers)',
      'James Taylor',
      'Amy Tan',
      'Calvin (Calvin and Hobbes)',
    ],
  ),
  Personality(
    id: 11,
    title: 'ENFP',
    subtitle: 'Compassioate Explorers',
    logo: 'assets/personality-logo/ENFP.png',
    focus: 'Use creativity and communication to foster growth in others',
    discription: '',
    fameType: 'The Motivator/Champion',
    careers: [
      'Counseling',
      'Teaching',
      'Religion',
      'Arts',
    ],
    celebrities: [
      'Dave Thomas (Wendy\'s)',
      'Meg Ryan',
      'Regis Philbin',
      'Dr. Doug Ross (ER)',
      'Ariel (The Little Mermaid)',
    ],
  ),
  Personality(
    id: 12,
    title: 'ENFJ',
    subtitle: 'Insightful Contributors',
    logo: 'assets/personality-logo/ENFJ.png',
    focus: 'Help others with their emotional, intellectual and spritual growth',
    discription: '',
    fameType: 'The Educator/Teacher',
    careers: [
      'Religion',
      'Arts',
      'Teaching',
    ],
    celebrities: [
      'Diane Sawyer',
      'Oprah Winfrey',
      'Martin Luther King, Jr.',
      'Lauren Graham (Gilmore Girls)',
      'Ben Affleck',
    ],
  ),
  Personality(
    id: 13,
    title: 'INTJ',
    subtitle: 'Logical Visionaries',
    logo: 'assets/personality-logo/INTJ.png',
    focus:
        'Use intellectual creativity and technicla knowledge to conceptulize analyze and get tasks done',
    discription: '',
    fameType: 'The Inventor/Mastermind',
    careers: [
      'Scientific Field',
      'Technical Field',
      'Computers',
      'Law',
    ],
    celebrities: [
      'Ulysses S. Grant',
      'Arnold Schwarzenegger Rudy Giuliani',
      'Donald Rumsfeld',
      'General Colin Powell',
    ],
  ),
  Personality(
    id: 14,
    title: 'INTP',
    subtitle: 'Insightful Analyzers',
    logo: 'assets/personality-logo/INTP.png',
    focus:
        'Apply objective analysis of problems and technical expertise in solitary environment',
    discription: '',
    fameType: 'The Logician/Architect',
    careers: [
      'Scientific Field',
      'Technical Field',
    ],
    celebrities: [
      'Socrates',
      'Charles Darwin',
      'Albert Einstein',
      'Mikhail Baryshnikov',
      'Nelson Mandela',
      'Steven Spielberg',
    ],
  ),
  Personality(
    id: 15,
    title: 'ENTP',
    subtitle: 'Logical Explorers',
    logo: 'assets/personality-logo/ENTP.png',
    focus: 'Continuously take on new challanges and solve problems',
    discription: '',
    fameType: 'The Strategizer/Inventor)',
    careers: [
      'Science',
      'Management',
      'Technilogy',
      'Arts',
    ],
    celebrities: [
      'Benjamin Franklin',
      'Walt Disney',
      'Red Auerbach',
      'Vin Baker',
      'Bugs Bunny',
    ],
  ),
  Personality(
    id: 16,
    title: 'ENTJ',
    subtitle: 'Insightful Expeditors',
    logo: 'assets/personality-logo/ENTJ.png',
    focus:
        'Use analsis, strategic-planning and organization to get tasks completed',
    discription: '',
    fameType: 'The CEO/Field Marshal',
    careers: [
      'Management',
      'Leadership',
    ],
    celebrities: [
      'Napoleon Bonaparte ',
      'Richard M. Nixon ',
      'Sigourney Weaver',
      'Margaret Thatcher',
      'Alan Greenspan',
    ],
  ),
];
